# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' function description
#' 
#' @param cog integer
#' @param c integer
#' @param m integer
#' @param d double
#' @export
probcpp <- function(cog, c, m, d) {
    .Call('_batson_app_pkg_probcpp', PACKAGE = 'batson.app.pkg', cog, c, m, d)
}

#' Likelihood function
#' 
#' x, col 2 should be number cognizable, 3 be total, 4 be cognizable
#' @param x NumericMatrix
#' @param L bool
#' @param d double
#' @export
Lk_cpp <- function(d, x, L) {
    .Call('_batson_app_pkg_Lk_cpp', PACKAGE = 'batson.app.pkg', d, x, L)
}

#' function description
#' 
#' @param theta descrip
#' @param mu descrip
#' @param std descrip
#' @export
Priorcpp <- function(theta, mu, std) {
    .Call('_batson_app_pkg_Priorcpp', PACKAGE = 'batson.app.pkg', theta, mu, std)
}

#' make_posterior function description
#' 
#' @param x descrip
#' @param niter descrip
#' @param theta_start_val descrip
#' @param theta_proposal_sd descrip
#' @param prior_mean The prior mean
#' @param prior_sd The prior standard deviation
#' @export
make_posterior <- function(x, niter, theta_start_val, theta_proposal_sd, prior_mean, prior_sd) {
    .Call('_batson_app_pkg_make_posterior', PACKAGE = 'batson.app.pkg', x, niter, theta_start_val, theta_proposal_sd, prior_mean, prior_sd)
}

#' function description
#' 
#' @param x NumericMatrix
#' @param L bool
#' @param d double
#' @export
Lk_cpp_p <- function(d, x, L) {
    .Call('_batson_app_pkg_Lk_cpp_p', PACKAGE = 'batson.app.pkg', d, x, L)
}

Priorcpp_p <- function(theta, mu, std, x, a0) {
    .Call('_batson_app_pkg_Priorcpp_p', PACKAGE = 'batson.app.pkg', theta, mu, std, x, a0)
}

make_posterior_p <- function(x, x_p, a0, niter, theta_start_val, theta_proposal_sd, prior_mean, prior_sd) {
    .Call('_batson_app_pkg_make_posterior_p', PACKAGE = 'batson.app.pkg', x, x_p, a0, niter, theta_start_val, theta_proposal_sd, prior_mean, prior_sd)
}

make_posterior_prior <- function(x_p, a0, niter, theta_start_val, theta_proposal_sd, prior_mean, prior_sd) {
    .Call('_batson_app_pkg_make_posterior_prior', PACKAGE = 'batson.app.pkg', x_p, a0, niter, theta_start_val, theta_proposal_sd, prior_mean, prior_sd)
}

