# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

probcpp <- function(cog, c, m, d) {
    .Call('_batson_app_pkg_probcpp', PACKAGE = 'batson.app.pkg', cog, c, m, d)
}

Lk_cpp <- function(d, x, L) {
    .Call('_batson_app_pkg_Lk_cpp', PACKAGE = 'batson.app.pkg', d, x, L)
}

Priorcpp <- function(theta, mu, std) {
    .Call('_batson_app_pkg_Priorcpp', PACKAGE = 'batson.app.pkg', theta, mu, std)
}

make_posterior <- function(x, niter, theta_start_val, theta_proposal_sd, prior_mean, prior_sd) {
    .Call('_batson_app_pkg_make_posterior', PACKAGE = 'batson.app.pkg', x, niter, theta_start_val, theta_proposal_sd, prior_mean, prior_sd)
}

Lk_cpp_p <- function(d, x, L) {
    .Call('_batson_app_pkg_Lk_cpp_p', PACKAGE = 'batson.app.pkg', d, x, L)
}

Priorcpp_p <- function(theta, mu, std, x, a0) {
    .Call('_batson_app_pkg_Priorcpp_p', PACKAGE = 'batson.app.pkg', theta, mu, std, x, a0)
}

make_posterior_p <- function(x, x_p, a0, niter, theta_start_val, theta_proposal_sd, prior_mean, prior_sd) {
    .Call('_batson_app_pkg_make_posterior_p', PACKAGE = 'batson.app.pkg', x, x_p, a0, niter, theta_start_val, theta_proposal_sd, prior_mean, prior_sd)
}

make_posterior_prior <- function(x_p, a0, niter, theta_start_val, theta_proposal_sd, prior_mean, prior_sd) {
    .Call('_batson_app_pkg_make_posterior_prior', PACKAGE = 'batson.app.pkg', x_p, a0, niter, theta_start_val, theta_proposal_sd, prior_mean, prior_sd)
}

